documento:
    pattern:  /
    defaults: { _controller: "TramiteBundle:Documento:index" }

documento_show:
    pattern:  /{id}/show
    defaults: { _controller: "TramiteBundle:Documento:show" }

documento_new:
    pattern:  /new
    defaults: { _controller: "TramiteBundle:Documento:new" }

documento_create:
    pattern:  /create
    defaults: { _controller: "TramiteBundle:Documento:create" }
    requirements: { _method: post }

documento_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "TramiteBundle:Documento:edit" }

documento_update:
    pattern:  /{id}/update
    defaults: { _controller: "TramiteBundle:Documento:update" }
    requirements: { _method: post|put }

documento_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "TramiteBundle:Documento:delete" }
    requirements: { _method: post|delete }
